# This docker-compose file is created based on the official file: https://github.com/bitnami/containers/blob/main/bitnami/spark/3.3/debian-11/docker-compose.yml

version: '3'

services:

  spark-master:
    image: bbccorp/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

      - S3_SERVER=http://minio:9000
      - S3_ACCESS_KEY=admin
      - S3_SECRET_KEY=password

    volumes:
      - ./samples:/opt/bitnami/spark/samples
    depends_on:
      - minio
    ports:
      - '8080:8080'
    networks:
      spark_net:


  spark-worker:
    image: bbccorp/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark

      - S3_SERVER=http://minio:9000
      - S3_ACCESS_KEY=admin
      - S3_SECRET_KEY=password
    volumes:
      - ./samples:/opt/bitnami/spark/samples
    depends_on:
      - minio
      - spark-master
    networks:
      spark_net:


  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - 9001:9001
      - 9000:9000
    command: [ "server", "/data", "--console-address", ":9001" ]
    networks:
      spark_net:


  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c " until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done; /usr/bin/mc rm -r --force minio/test; /usr/bin/mc mb minio/test; /usr/bin/mc policy set public minio/test; tail -f /dev/null "
    networks:
      spark_net:


networks:
  spark_net:
